version: "3.9"
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: modern_dentistry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "012345"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - modern-net

  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - modern-net

  modern-dentistry:
    image: rustemh/modern-dentistry:latest
    container_name: modern-dentistry
    depends_on:
      - postgres-db
      - redis-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "5555:5555"
    volumes:
      - "/home/media:/app/media"
    networks:
      - modern-net

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/media:/home/media:ro
    networks:
      - modern-net

networks:
  modern-net:
    driver: bridge

volumes:
  postgres_data:
