spring:
  profiles:
    active: prod
  application:
    name: modern-dentistry
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 6000000
      refresh-token:
        expiration: 604800000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:5555}
  address: 0.0.0.0
